//! The 127-entry `ACHIEVEMENT_DEFS` table and its lookup helpers.

use super::*;

/// C `static const AchievementDef achievement_defs[ACHIEVEMENT_TYPE_COUNT]`
/// (`achievement.c:44-326`), copied digit for digit (Steam ids, display
/// names, descriptions, categories, targets - all C table entries have
/// `hidden = 0`, so none are hidden achievements today).
pub const ACHIEVEMENT_DEFS: [AchievementDef; ACHIEVEMENT_TYPE_COUNT] = [
    AchievementDef {
        ty: AchievementType::StartedUgaris,
        steam_id: "STARTED_UGARIS",
        name: "Started Ugaris",
        description: "Launch Ugaris through Steam",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::RisingBeginner,
        steam_id: "RISING_BEGINNER",
        name: "Rising Beginner",
        description: "Reach level 10",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::ExperiencedHero,
        steam_id: "EXPERIENCED_HERO",
        name: "Experienced Hero",
        description: "Reach level 20",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::UgarisVeteran,
        steam_id: "UGARIS_VETERAN",
        name: "Ugaris Veteran",
        description: "Reach level 50",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::LegendaryAdventurer,
        steam_id: "LEGENDARY_ADVENTURER",
        name: "Legendary Adventurer",
        description: "Reach level 75",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::DemonSlayer,
        steam_id: "DEMON_SLAYER",
        name: "Demon Slayer",
        description: "Reach level 100",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterOfHell,
        steam_id: "MASTER_OF_HELL",
        name: "Master of Hell",
        description: "Reach level 150",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterOfUgaris,
        steam_id: "MASTER_OF_UGARIS",
        name: "Master of Ugaris",
        description: "Reach level 200",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::FirstBlood,
        steam_id: "FIRST_BLOOD",
        name: "First Blood",
        description: "Defeat your first enemy",
        category: AchCategory::Combat,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Ladykiller,
        steam_id: "LADYKILLER",
        name: "Ladykiller",
        description: "Defeat Islena",
        category: AchCategory::Combat,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::ArenaCombatant,
        steam_id: "ARENA_COMBATANT",
        name: "Arena Combatant",
        description: "Defeat another player in PvP",
        category: AchCategory::Combat,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::SlayerOfWizards,
        steam_id: "SLAYER_OF_WIZARDS",
        name: "Slayer of Wizards",
        description: "Kill Yendor",
        category: AchCategory::Combat,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Dragonsbane,
        steam_id: "DRAGONSBANE",
        name: "Dragonsbane",
        description: "Complete Carlos' Dragons quest",
        category: AchCategory::Combat,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::DemonLordsDemise,
        steam_id: "DEMON_LORDS_DEMISE",
        name: "Demon Lord's Demise",
        description: "Kill a demon lord",
        category: AchCategory::Combat,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::SlayerOfDemonLords,
        steam_id: "SLAYER_OF_DEMON_LORDS",
        name: "Slayer of Demon Lords",
        description: "Kill 20 unique demon lords",
        category: AchCategory::Combat,
        target: 20,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::FiendFighter,
        steam_id: "FIEND_FIGHTER",
        name: "Fiend Fighter",
        description: "Defeat 100 demons",
        category: AchCategory::Combat,
        target: 100,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Demonbane,
        steam_id: "DEMONBANE",
        name: "Demonbane",
        description: "Defeat 2,500 demons",
        category: AchCategory::Combat,
        target: 2500,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::DreadDestroyer,
        steam_id: "DREAD_DESTROYER",
        name: "Dread Destroyer",
        description: "Defeat 15,000 demons",
        category: AchCategory::Combat,
        target: 15000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::DemonicExterminator,
        steam_id: "DEMONIC_EXTERMINATOR",
        name: "Demonic Exterminator",
        description: "Defeat 250,000 demons",
        category: AchCategory::Combat,
        target: 250000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::UgarisPathfinder,
        steam_id: "UGARIS_PATHFINDER",
        name: "Ugaris Pathfinder",
        description: "Discover and travel to Aston",
        category: AchCategory::Exploration,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::TravellerOfAstonia,
        steam_id: "TRAVELLER_OF_ASTONIA",
        name: "Traveller of Astonia",
        description: "Visit all major cities",
        category: AchCategory::Exploration,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::UndergroundExplorer,
        steam_id: "UNDERGROUND_EXPLORER",
        name: "Underground Explorer",
        description: "Activate all Earth Underground teleports",
        category: AchCategory::Exploration,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::ExplorerOfAstonia,
        steam_id: "EXPLORER_OF_ASTONIA",
        name: "Explorer of Astonia",
        description: "Activate all Rodney's map teleports",
        category: AchCategory::Exploration,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GreatExplorer,
        steam_id: "GREAT_EXPLORER",
        name: "Great Explorer",
        description: "Complete Finding Arkhata quest",
        category: AchCategory::Exploration,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::AHelpingHand,
        steam_id: "A_HELPING_HAND",
        name: "A Helping Hand",
        description: "Complete Lydia's potion quest",
        category: AchCategory::Quests,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Quester,
        steam_id: "QUESTER",
        name: "Quester",
        description: "Use the repeat option on any quest",
        category: AchCategory::Quests,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GreenThumb,
        steam_id: "GREEN_THUMB",
        name: "Green Thumb",
        description: "Gather 10 flowers",
        category: AchCategory::Crafting,
        target: 10,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::BotanyEnthusiast,
        steam_id: "BOTANY_ENTHUSIAST",
        name: "Botany Enthusiast",
        description: "Gather 50 flowers",
        category: AchCategory::Crafting,
        target: 50,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::NaturesFriend,
        steam_id: "NATURES_FRIEND",
        name: "Nature's Friend",
        description: "Gather 200 flowers",
        category: AchCategory::Crafting,
        target: 200,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Herbalist,
        steam_id: "HERBALIST",
        name: "Herbalist",
        description: "Gather 500 flowers",
        category: AchCategory::Crafting,
        target: 500,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterHerbalist,
        steam_id: "MASTER_HERBALIST",
        name: "Master Herbalist",
        description: "Gather 1000 flowers",
        category: AchCategory::Crafting,
        target: 1000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MushroomHunter,
        steam_id: "MUSHROOM_HUNTER",
        name: "Mushroom Hunter",
        description: "Gather 10 mushrooms",
        category: AchCategory::Crafting,
        target: 10,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::FungusFinder,
        steam_id: "FUNGUS_FINDER",
        name: "Fungus Finder",
        description: "Gather 50 mushrooms",
        category: AchCategory::Crafting,
        target: 50,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::SporeSeeker,
        steam_id: "SPORE_SEEKER",
        name: "Spore Seeker",
        description: "Gather 200 mushrooms",
        category: AchCategory::Crafting,
        target: 200,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MushroomMaster,
        steam_id: "MUSHROOM_MASTER",
        name: "Mushroom Master",
        description: "Gather 500 mushrooms",
        category: AchCategory::Crafting,
        target: 500,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Mycologist,
        steam_id: "MYCOLOGIST",
        name: "Mycologist",
        description: "Gather 1000 mushrooms",
        category: AchCategory::Crafting,
        target: 1000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::BerryPicker,
        steam_id: "BERRY_PICKER",
        name: "Berry Picker",
        description: "Gather 10 berries",
        category: AchCategory::Crafting,
        target: 10,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::FruitForager,
        steam_id: "FRUIT_FORAGER",
        name: "Fruit Forager",
        description: "Gather 50 berries",
        category: AchCategory::Crafting,
        target: 50,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::BerryEnthusiast,
        steam_id: "BERRY_ENTHUSIAST",
        name: "Berry Enthusiast",
        description: "Gather 200 berries",
        category: AchCategory::Crafting,
        target: 200,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::HarvestHero,
        steam_id: "HARVEST_HERO",
        name: "Harvest Hero",
        description: "Gather 500 berries",
        category: AchCategory::Crafting,
        target: 500,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterGatherer,
        steam_id: "MASTER_GATHERER",
        name: "Master Gatherer",
        description: "Gather 1000 berries",
        category: AchCategory::Crafting,
        target: 1000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Alchemist,
        steam_id: "ALCHEMIST",
        name: "Alchemist",
        description: "Brew 10 potions",
        category: AchCategory::Crafting,
        target: 10,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::JourneymanBrewer,
        steam_id: "JOURNEYMAN_BREWER",
        name: "Journeyman Brewer",
        description: "Brew 50 potions",
        category: AchCategory::Crafting,
        target: 50,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::ArcaneAlchemist,
        steam_id: "ARCANE_ALCHEMIST",
        name: "Arcane Alchemist",
        description: "Brew 100 potions",
        category: AchCategory::Crafting,
        target: 100,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GrandmasterBrewer,
        steam_id: "GRANDMASTER_BREWER",
        name: "Grandmaster Brewer",
        description: "Brew 200 potions",
        category: AchCategory::Crafting,
        target: 200,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GoldLooter,
        steam_id: "GOLD_LOOTER",
        name: "Gold Looter",
        description: "Find and open the 80s mine gold room chest",
        category: AchCategory::Crafting,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::WellPaidGatherer,
        steam_id: "WELL_PAID_GATHERER",
        name: "Well-Paid Gatherer",
        description: "Hand in every alchemy item to Reskin",
        category: AchCategory::Crafting,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Solved,
        steam_id: "SOLVED",
        name: "Solved!",
        description: "Solve one pentagram quest",
        category: AchCategory::Pentagram,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::FullOfSolves,
        steam_id: "FULL_OF_SOLVES",
        name: "Full of Solves",
        description: "Solve 20 pentagram quests",
        category: AchCategory::Pentagram,
        target: 20,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::RuneMaster,
        steam_id: "RUNE_MASTER",
        name: "Rune Master",
        description: "Solve 100 pentagram quests",
        category: AchCategory::Pentagram,
        target: 100,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GrandmasterPentagram,
        steam_id: "GRANDMASTER_PENTAGRAM",
        name: "Grandmaster of the Pentagram",
        description: "Solve 500 pentagram quests",
        category: AchCategory::Pentagram,
        target: 500,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::EarthboundNovice,
        steam_id: "EARTHBOUND_NOVICE",
        name: "Earthbound Novice",
        description: "Solve a pentagram in Earth Pents",
        category: AchCategory::Pentagram,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::FlameInitiate,
        steam_id: "FLAME_INITIATE",
        name: "Flame Initiate",
        description: "Solve a pentagram in Fire Pents",
        category: AchCategory::Pentagram,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::FightingTheFrost,
        steam_id: "FIGHTING_THE_FROST",
        name: "Fighting the Frost",
        description: "Solve a pentagram in Ice Pents",
        category: AchCategory::Pentagram,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::ThroughGatesOfHell,
        steam_id: "THROUGH_GATES_OF_HELL",
        name: "Through the Gates of Hell",
        description: "Solve a pentagram in Hell Pents",
        category: AchCategory::Pentagram,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::HappyGoLucky,
        steam_id: "HAPPY_GO_LUCKY",
        name: "Happy Go Lucky",
        description: "Hit a lucky pentagram",
        category: AchCategory::Pentagram,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::FavoredByFortune,
        steam_id: "FAVORED_BY_FORTUNE",
        name: "Favored by Fortune",
        description: "Two lucky pents on the same solve",
        category: AchCategory::Pentagram,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::FiveInARow,
        steam_id: "FIVE_IN_A_ROW",
        name: "5 in a Row",
        description: "Get 5 pents the same color",
        category: AchCategory::Pentagram,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::TreasureHunter,
        steam_id: "TREASURE_HUNTER",
        name: "Treasure Hunter",
        description: "Open 50 chests",
        category: AchCategory::Collection,
        target: 50,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::EarthRocks,
        steam_id: "EARTH_ROCKS",
        name: "Earth Rocks!",
        description: "Collect 50 Earth stones",
        category: AchCategory::Collection,
        target: 50,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::FireRocks,
        steam_id: "FIRE_ROCKS",
        name: "Fire Rocks!",
        description: "Collect 100 Fire stones",
        category: AchCategory::Collection,
        target: 100,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::IceRocks,
        steam_id: "ICE_ROCKS",
        name: "Ice Rocks!",
        description: "Collect 1000 Ice stones",
        category: AchCategory::Collection,
        target: 1000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::WeaponNovice,
        steam_id: "WEAPON_NOVICE",
        name: "Weapon Novice",
        description: "Level a weapon skill to 10",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterOfArms,
        steam_id: "MASTER_OF_ARMS",
        name: "Master of Arms",
        description: "Level a weapon skill to 110",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::ApprenticeMagic,
        steam_id: "APPRENTICE_MAGIC",
        name: "Apprentice of Magic",
        description: "Level Fire or Lightning magic to 10",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::IntermediateMagic,
        steam_id: "INTERMEDIATE_MAGIC",
        name: "Intermediate of Magic",
        description: "Level Fire or Lightning magic to 50",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterOfMagic,
        steam_id: "MASTER_OF_MAGIC",
        name: "Master of Magic",
        description: "Level Fire or Lightning magic to 110",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::ApprenticeFighting,
        steam_id: "APPRENTICE_FIGHTING",
        name: "Apprentice of Fighting",
        description: "Level Attack or Parry to 10",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::IntermediateFighting,
        steam_id: "INTERMEDIATE_FIGHTING",
        name: "Intermediate of Fighting",
        description: "Level Attack or Parry to 50",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterOfFighting,
        steam_id: "MASTER_OF_FIGHTING",
        name: "Master of Fighting",
        description: "Level Attack or Parry to 110",
        category: AchCategory::Progression,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::ClanMember,
        steam_id: "CLAN_MEMBER",
        name: "Clan Member",
        description: "Join a Clan",
        category: AchCategory::Social,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::ClanMaster,
        steam_id: "CLAN_MASTER",
        name: "Clan Master",
        description: "Found your own clan",
        category: AchCategory::Social,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::ClubMember,
        steam_id: "CLUB_MEMBER",
        name: "Club Member",
        description: "Join a club",
        category: AchCategory::Social,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::ClubMaster,
        steam_id: "CLUB_MASTER",
        name: "Club Master",
        description: "Found a club",
        category: AchCategory::Social,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::TrustButVerify,
        steam_id: "TRUST_BUT_VERIFY",
        name: "Trust, but Verify",
        description: "Use Trader for a trade with another player",
        category: AchCategory::Social,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::HardcoreHero,
        steam_id: "HARDCORE_HERO",
        name: "Hardcore Hero",
        description: "Reach level 50 on a hardcore character",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::HardcoreLegend,
        steam_id: "HARDCORE_LEGEND",
        name: "Hardcore Legend",
        description: "Reach level 100 on a hardcore character",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MilitaryVeteran,
        steam_id: "MILITARY_VETERAN",
        name: "Military Veteran",
        description: "Complete 100 military missions",
        category: AchCategory::Special,
        target: 100,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::TunnelRat,
        steam_id: "TUNNEL_RAT",
        name: "Tunnel Rat",
        description: "Complete all tunnel levels",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterTrader,
        steam_id: "MASTER_TRADER",
        name: "Master Trader",
        description: "Max out the Trader profession",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterAlchemist,
        steam_id: "MASTER_ALCHEMIST",
        name: "Master Alchemist",
        description: "Max out the Alchemist profession",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterHerbalistProf,
        steam_id: "MASTER_HERBALIST_PROF",
        name: "Master Herbalist (Prof)",
        description: "Max out the Herbalist profession",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterMiner,
        steam_id: "MASTER_MINER",
        name: "Master Miner",
        description: "Max out the Miner profession",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterAthlete,
        steam_id: "MASTER_ATHLETE",
        name: "Master Athlete",
        description: "Max out the Athlete profession",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterAssassin,
        steam_id: "MASTER_ASSASSIN",
        name: "Master Assassin",
        description: "Max out the Assassin profession",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterThief,
        steam_id: "MASTER_THIEF",
        name: "Master Thief",
        description: "Max out the Thief profession",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterLightWarrior,
        steam_id: "MASTER_LIGHT_WARRIOR",
        name: "Master of Light",
        description: "Max out the Light Warrior profession",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterDarkWarrior,
        steam_id: "MASTER_DARK_WARRIOR",
        name: "Master of Darkness",
        description: "Max out the Dark Warrior profession",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterMercenary,
        steam_id: "MASTER_MERCENARY",
        name: "Master Mercenary",
        description: "Max out the Mercenary profession",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::MasterClanWarrior,
        steam_id: "MASTER_CLAN_WARRIOR",
        name: "Master Clan Warrior",
        description: "Max out the Clan Warrior profession",
        category: AchCategory::Special,
        target: 0,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::SilverNovice,
        steam_id: "SILVER_NOVICE",
        name: "Silver Novice",
        description: "Mine 100 silver units",
        category: AchCategory::Collection,
        target: 100,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::SilverCollector,
        steam_id: "SILVER_COLLECTOR",
        name: "Silver Collector",
        description: "Mine 1,000 silver units",
        category: AchCategory::Collection,
        target: 1000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::SilverHoarder,
        steam_id: "SILVER_HOARDER",
        name: "Silver Hoarder",
        description: "Mine 10,000 silver units",
        category: AchCategory::Collection,
        target: 10000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::SilverBaron,
        steam_id: "SILVER_BARON",
        name: "Silver Baron",
        description: "Mine 100,000 silver units",
        category: AchCategory::Collection,
        target: 100000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::SilverTycoon,
        steam_id: "SILVER_TYCOON",
        name: "Silver Tycoon",
        description: "Mine 1,000,000 silver units",
        category: AchCategory::Collection,
        target: 1000000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::SilverMagnate,
        steam_id: "SILVER_MAGNATE",
        name: "Silver Magnate",
        description: "Mine 10,000,000 silver units",
        category: AchCategory::Collection,
        target: 10000000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::SilverLegend,
        steam_id: "SILVER_LEGEND",
        name: "Silver Legend",
        description: "Mine 50,000,000 silver units",
        category: AchCategory::Collection,
        target: 50000000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GoldNovice,
        steam_id: "GOLD_NOVICE",
        name: "Gold Novice",
        description: "Mine 50 gold units",
        category: AchCategory::Collection,
        target: 50,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GoldCollector,
        steam_id: "GOLD_COLLECTOR",
        name: "Gold Collector",
        description: "Mine 500 gold units",
        category: AchCategory::Collection,
        target: 500,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GoldHoarder,
        steam_id: "GOLD_HOARDER",
        name: "Gold Hoarder",
        description: "Mine 5,000 gold units",
        category: AchCategory::Collection,
        target: 5000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GoldBaron,
        steam_id: "GOLD_BARON",
        name: "Gold Baron",
        description: "Mine 50,000 gold units",
        category: AchCategory::Collection,
        target: 50000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GoldTycoon,
        steam_id: "GOLD_TYCOON",
        name: "Gold Tycoon",
        description: "Mine 500,000 gold units",
        category: AchCategory::Collection,
        target: 500000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GoldMagnate,
        steam_id: "GOLD_MAGNATE",
        name: "Gold Magnate",
        description: "Mine 5,000,000 gold units",
        category: AchCategory::Collection,
        target: 5000000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::GoldLegend,
        steam_id: "GOLD_LEGEND",
        name: "Gold Legend",
        description: "Mine 50,000,000 gold units",
        category: AchCategory::Collection,
        target: 50000000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::CoinCollector,
        steam_id: "COIN_COLLECTOR",
        name: "Coin Collector",
        description: "Earn 10,000 gold total",
        category: AchCategory::Collection,
        target: 10000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::WealthyAdventurer,
        steam_id: "WEALTHY_ADVENTURER",
        name: "Wealthy Adventurer",
        description: "Earn 100,000 gold total",
        category: AchCategory::Collection,
        target: 100000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::RichNoble,
        steam_id: "RICH_NOBLE",
        name: "Rich Noble",
        description: "Earn 1,000,000 gold total",
        category: AchCategory::Collection,
        target: 1000000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Millionaire,
        steam_id: "MILLIONAIRE",
        name: "Millionaire",
        description: "Earn 10,000,000 gold total",
        category: AchCategory::Collection,
        target: 10000000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Recruit,
        steam_id: "RECRUIT",
        name: "Recruit",
        description: "Complete 10 military missions",
        category: AchCategory::Combat,
        target: 10,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Soldier,
        steam_id: "SOLDIER",
        name: "Soldier",
        description: "Complete 25 military missions",
        category: AchCategory::Combat,
        target: 25,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Commander,
        steam_id: "COMMANDER",
        name: "Commander",
        description: "Complete 250 military missions",
        category: AchCategory::Combat,
        target: 250,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::General,
        steam_id: "GENERAL",
        name: "General",
        description: "Complete 500 military missions",
        category: AchCategory::Combat,
        target: 500,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::WarLegend,
        steam_id: "WAR_LEGEND",
        name: "War Legend",
        description: "Complete 1,000 military missions",
        category: AchCategory::Combat,
        target: 1000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::TunnelExplorer,
        steam_id: "TUNNEL_EXPLORER",
        name: "Tunnel Explorer",
        description: "Complete 10 tunnel sections",
        category: AchCategory::Exploration,
        target: 10,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::TunnelRunner,
        steam_id: "TUNNEL_RUNNER",
        name: "Tunnel Runner",
        description: "Complete 25 tunnel sections",
        category: AchCategory::Exploration,
        target: 25,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::TunnelVeteran,
        steam_id: "TUNNEL_VETERAN",
        name: "Tunnel Veteran",
        description: "Complete 50 tunnel sections",
        category: AchCategory::Exploration,
        target: 50,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Looter,
        steam_id: "LOOTER",
        name: "Looter",
        description: "Open 10 chests",
        category: AchCategory::Collection,
        target: 10,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::TreasureMaster,
        steam_id: "TREASURE_MASTER",
        name: "Treasure Master",
        description: "Open 100 chests",
        category: AchCategory::Collection,
        target: 100,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::LegendaryLooter,
        steam_id: "LEGENDARY_LOOTER",
        name: "Legendary Looter",
        description: "Open 500 chests",
        category: AchCategory::Collection,
        target: 500,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::PotionMaster,
        steam_id: "POTION_MASTER",
        name: "Potion Master",
        description: "Brew 500 potions",
        category: AchCategory::Crafting,
        target: 500,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::LegendaryBrewer,
        steam_id: "LEGENDARY_BREWER",
        name: "Legendary Brewer",
        description: "Brew 1,000 potions",
        category: AchCategory::Crafting,
        target: 1000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::DedicatedPlayer,
        steam_id: "DEDICATED_PLAYER",
        name: "Dedicated Player",
        description: "Play for 24 hours total",
        category: AchCategory::Special,
        target: 1440,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::VeteranPlayer,
        steam_id: "VETERAN_PLAYER",
        name: "Veteran Player",
        description: "Play for 100 hours total",
        category: AchCategory::Special,
        target: 6000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::UgarisLifer,
        steam_id: "UGARIS_LIFER",
        name: "Ugaris Lifer",
        description: "Play for 500 hours total",
        category: AchCategory::Special,
        target: 30000,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Regular,
        steam_id: "REGULAR",
        name: "Regular",
        description: "Log in 7 days in a row",
        category: AchCategory::Special,
        target: 7,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Committed,
        steam_id: "COMMITTED",
        name: "Committed",
        description: "Log in 30 days in a row",
        category: AchCategory::Special,
        target: 30,
        hidden: false,
    },
    AchievementDef {
        ty: AchievementType::Devoted,
        steam_id: "DEVOTED",
        name: "Devoted",
        description: "Log in 100 days in a row",
        category: AchCategory::Special,
        target: 100,
        hidden: false,
    },
];

/// C `achievement_get_def` (`achievement.c:560-565`).
pub fn achievement_def(ty: AchievementType) -> &'static AchievementDef {
    &ACHIEVEMENT_DEFS[ty as usize]
}

/// C `achievement_area_to_pent_index` (`achievement.c:378-391`).
pub fn area_to_pent_index(area_id: i32) -> Option<PentArea> {
    match area_id {
        4 => Some(PentArea::Earth),
        7 => Some(PentArea::Fire),
        9 => Some(PentArea::Ice),
        34 => Some(PentArea::Hell),
        _ => None,
    }
}
