//! Achievement type/category enums and the `AchievementDef` definition record.

/// C `#define MAX_ACHIEVEMENTS 128` (`achievement.h:18`).
pub const MAX_ACHIEVEMENTS: usize = 128;

/// C `ACHIEVEMENT_TYPE_COUNT` (`achievement.h:211`): 127 real achievement
/// types precede the trailing count marker in the C enum.
pub const ACHIEVEMENT_TYPE_COUNT: usize = 127;

/// C `PentArea` (`achievement.h:215`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum PentArea {
    Earth = 0,
    Fire = 1,
    Ice = 2,
    Hell = 3,
}

/// C `PENT_AREA_COUNT`.
pub const PENT_AREA_COUNT: usize = 4;

/// C `ServerAchCat` (`achievement.h:23-34`); numeric values must match the
/// protocol's `AchievementCategory` (`mod_achievements.h:52-62`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum AchCategory {
    Progression = 0,
    Combat = 1,
    Exploration = 2,
    Quests = 3,
    Crafting = 4,
    Social = 5,
    Pentagram = 6,
    Collection = 7,
    Special = 8,
}

/// C `AchievementType` (`achievement.h:38-212`), copied in exact
/// declaration order so `as usize` matches the C enum's numeric value used
/// to index `achievement_defs`/`AccountAchievements::achievements`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum AchievementType {
    StartedUgaris = 0,
    RisingBeginner = 1,
    ExperiencedHero = 2,
    UgarisVeteran = 3,
    LegendaryAdventurer = 4,
    DemonSlayer = 5,
    MasterOfHell = 6,
    MasterOfUgaris = 7,
    FirstBlood = 8,
    Ladykiller = 9,
    ArenaCombatant = 10,
    SlayerOfWizards = 11,
    Dragonsbane = 12,
    DemonLordsDemise = 13,
    SlayerOfDemonLords = 14,
    FiendFighter = 15,
    Demonbane = 16,
    DreadDestroyer = 17,
    DemonicExterminator = 18,
    UgarisPathfinder = 19,
    TravellerOfAstonia = 20,
    UndergroundExplorer = 21,
    ExplorerOfAstonia = 22,
    GreatExplorer = 23,
    AHelpingHand = 24,
    Quester = 25,
    GreenThumb = 26,
    BotanyEnthusiast = 27,
    NaturesFriend = 28,
    Herbalist = 29,
    MasterHerbalist = 30,
    MushroomHunter = 31,
    FungusFinder = 32,
    SporeSeeker = 33,
    MushroomMaster = 34,
    Mycologist = 35,
    BerryPicker = 36,
    FruitForager = 37,
    BerryEnthusiast = 38,
    HarvestHero = 39,
    MasterGatherer = 40,
    Alchemist = 41,
    JourneymanBrewer = 42,
    ArcaneAlchemist = 43,
    GrandmasterBrewer = 44,
    GoldLooter = 45,
    WellPaidGatherer = 46,
    Solved = 47,
    FullOfSolves = 48,
    RuneMaster = 49,
    GrandmasterPentagram = 50,
    EarthboundNovice = 51,
    FlameInitiate = 52,
    FightingTheFrost = 53,
    ThroughGatesOfHell = 54,
    HappyGoLucky = 55,
    FavoredByFortune = 56,
    FiveInARow = 57,
    TreasureHunter = 58,
    EarthRocks = 59,
    FireRocks = 60,
    IceRocks = 61,
    WeaponNovice = 62,
    MasterOfArms = 63,
    ApprenticeMagic = 64,
    IntermediateMagic = 65,
    MasterOfMagic = 66,
    ApprenticeFighting = 67,
    IntermediateFighting = 68,
    MasterOfFighting = 69,
    ClanMember = 70,
    ClanMaster = 71,
    ClubMember = 72,
    ClubMaster = 73,
    TrustButVerify = 74,
    HardcoreHero = 75,
    HardcoreLegend = 76,
    MilitaryVeteran = 77,
    TunnelRat = 78,
    MasterTrader = 79,
    MasterAlchemist = 80,
    MasterHerbalistProf = 81,
    MasterMiner = 82,
    MasterAthlete = 83,
    MasterAssassin = 84,
    MasterThief = 85,
    MasterLightWarrior = 86,
    MasterDarkWarrior = 87,
    MasterMercenary = 88,
    MasterClanWarrior = 89,
    SilverNovice = 90,
    SilverCollector = 91,
    SilverHoarder = 92,
    SilverBaron = 93,
    SilverTycoon = 94,
    SilverMagnate = 95,
    SilverLegend = 96,
    GoldNovice = 97,
    GoldCollector = 98,
    GoldHoarder = 99,
    GoldBaron = 100,
    GoldTycoon = 101,
    GoldMagnate = 102,
    GoldLegend = 103,
    CoinCollector = 104,
    WealthyAdventurer = 105,
    RichNoble = 106,
    Millionaire = 107,
    Recruit = 108,
    Soldier = 109,
    Commander = 110,
    General = 111,
    WarLegend = 112,
    TunnelExplorer = 113,
    TunnelRunner = 114,
    TunnelVeteran = 115,
    Looter = 116,
    TreasureMaster = 117,
    LegendaryLooter = 118,
    PotionMaster = 119,
    LegendaryBrewer = 120,
    DedicatedPlayer = 121,
    VeteranPlayer = 122,
    UgarisLifer = 123,
    Regular = 124,
    Committed = 125,
    Devoted = 126,
}

impl AchievementType {
    /// All 127 achievement types in C declaration/index order.
    pub const ALL: [AchievementType; ACHIEVEMENT_TYPE_COUNT] = [
        AchievementType::StartedUgaris,
        AchievementType::RisingBeginner,
        AchievementType::ExperiencedHero,
        AchievementType::UgarisVeteran,
        AchievementType::LegendaryAdventurer,
        AchievementType::DemonSlayer,
        AchievementType::MasterOfHell,
        AchievementType::MasterOfUgaris,
        AchievementType::FirstBlood,
        AchievementType::Ladykiller,
        AchievementType::ArenaCombatant,
        AchievementType::SlayerOfWizards,
        AchievementType::Dragonsbane,
        AchievementType::DemonLordsDemise,
        AchievementType::SlayerOfDemonLords,
        AchievementType::FiendFighter,
        AchievementType::Demonbane,
        AchievementType::DreadDestroyer,
        AchievementType::DemonicExterminator,
        AchievementType::UgarisPathfinder,
        AchievementType::TravellerOfAstonia,
        AchievementType::UndergroundExplorer,
        AchievementType::ExplorerOfAstonia,
        AchievementType::GreatExplorer,
        AchievementType::AHelpingHand,
        AchievementType::Quester,
        AchievementType::GreenThumb,
        AchievementType::BotanyEnthusiast,
        AchievementType::NaturesFriend,
        AchievementType::Herbalist,
        AchievementType::MasterHerbalist,
        AchievementType::MushroomHunter,
        AchievementType::FungusFinder,
        AchievementType::SporeSeeker,
        AchievementType::MushroomMaster,
        AchievementType::Mycologist,
        AchievementType::BerryPicker,
        AchievementType::FruitForager,
        AchievementType::BerryEnthusiast,
        AchievementType::HarvestHero,
        AchievementType::MasterGatherer,
        AchievementType::Alchemist,
        AchievementType::JourneymanBrewer,
        AchievementType::ArcaneAlchemist,
        AchievementType::GrandmasterBrewer,
        AchievementType::GoldLooter,
        AchievementType::WellPaidGatherer,
        AchievementType::Solved,
        AchievementType::FullOfSolves,
        AchievementType::RuneMaster,
        AchievementType::GrandmasterPentagram,
        AchievementType::EarthboundNovice,
        AchievementType::FlameInitiate,
        AchievementType::FightingTheFrost,
        AchievementType::ThroughGatesOfHell,
        AchievementType::HappyGoLucky,
        AchievementType::FavoredByFortune,
        AchievementType::FiveInARow,
        AchievementType::TreasureHunter,
        AchievementType::EarthRocks,
        AchievementType::FireRocks,
        AchievementType::IceRocks,
        AchievementType::WeaponNovice,
        AchievementType::MasterOfArms,
        AchievementType::ApprenticeMagic,
        AchievementType::IntermediateMagic,
        AchievementType::MasterOfMagic,
        AchievementType::ApprenticeFighting,
        AchievementType::IntermediateFighting,
        AchievementType::MasterOfFighting,
        AchievementType::ClanMember,
        AchievementType::ClanMaster,
        AchievementType::ClubMember,
        AchievementType::ClubMaster,
        AchievementType::TrustButVerify,
        AchievementType::HardcoreHero,
        AchievementType::HardcoreLegend,
        AchievementType::MilitaryVeteran,
        AchievementType::TunnelRat,
        AchievementType::MasterTrader,
        AchievementType::MasterAlchemist,
        AchievementType::MasterHerbalistProf,
        AchievementType::MasterMiner,
        AchievementType::MasterAthlete,
        AchievementType::MasterAssassin,
        AchievementType::MasterThief,
        AchievementType::MasterLightWarrior,
        AchievementType::MasterDarkWarrior,
        AchievementType::MasterMercenary,
        AchievementType::MasterClanWarrior,
        AchievementType::SilverNovice,
        AchievementType::SilverCollector,
        AchievementType::SilverHoarder,
        AchievementType::SilverBaron,
        AchievementType::SilverTycoon,
        AchievementType::SilverMagnate,
        AchievementType::SilverLegend,
        AchievementType::GoldNovice,
        AchievementType::GoldCollector,
        AchievementType::GoldHoarder,
        AchievementType::GoldBaron,
        AchievementType::GoldTycoon,
        AchievementType::GoldMagnate,
        AchievementType::GoldLegend,
        AchievementType::CoinCollector,
        AchievementType::WealthyAdventurer,
        AchievementType::RichNoble,
        AchievementType::Millionaire,
        AchievementType::Recruit,
        AchievementType::Soldier,
        AchievementType::Commander,
        AchievementType::General,
        AchievementType::WarLegend,
        AchievementType::TunnelExplorer,
        AchievementType::TunnelRunner,
        AchievementType::TunnelVeteran,
        AchievementType::Looter,
        AchievementType::TreasureMaster,
        AchievementType::LegendaryLooter,
        AchievementType::PotionMaster,
        AchievementType::LegendaryBrewer,
        AchievementType::DedicatedPlayer,
        AchievementType::VeteranPlayer,
        AchievementType::UgarisLifer,
        AchievementType::Regular,
        AchievementType::Committed,
        AchievementType::Devoted,
    ];
}

/// C `AchievementDef` (`achievement.h:279-286`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AchievementDef {
    pub ty: AchievementType,
    /// Steam API achievement id (`STEAM_ACH_*` in `mod_achievements.h`).
    pub steam_id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub category: AchCategory,
    /// Target for progress-based achievements (`0` = instant/one-time).
    pub target: u32,
    pub hidden: bool,
}
