//! Per-tick NPC and queued-event passes, one fn per legacy
//! driver/drain, grouped by area. `run_all` preserves the
//! exact pre-extraction execution order. New NPC plumbing
//! goes here, never in `main.rs`.

pub(crate) mod admin_tasks;
pub(crate) mod area1;
pub(crate) mod area11;
pub(crate) mod area12;
pub(crate) mod area13;
pub(crate) mod area16;
pub(crate) mod area17;
pub(crate) mod area19;
pub(crate) mod area2;
pub(crate) mod area20;
pub(crate) mod area22;
pub(crate) mod area3;
pub(crate) mod area30;
pub(crate) mod area32;
pub(crate) mod area4;
pub(crate) mod area8;
pub(crate) mod arena;
pub(crate) mod system;

use super::*;

#[allow(clippy::too_many_arguments)]
pub(crate) async fn run_all(
    world: &mut World,
    runtime: &mut ServerRuntime,
    zone_loader: &mut ZoneLoader,
    config: &ServerConfig,
    args: &Args,
    completed_actions: &[WorldActionCompletion],
    achievement_repository: &Option<ugaris_db::PgAchievementRepository>,
    character_repository: &Option<ugaris_db::PgCharacterRepository>,
    area_repository: &Option<ugaris_db::PgAreaRepository>,
    clan_repository: &Option<ugaris_db::PgClanRegistryRepository>,
    clan_log_repository: &Option<ugaris_db::PgClanLogRepository>,
    merchant_repository: &Option<ugaris_db::PgMerchantRepository>,
    military_master_storage_repository: &Option<ugaris_db::PgMilitaryMasterStorageRepository>,
    military_advisor_storage_repository: &Option<ugaris_db::PgMilitaryAdvisorStorageRepository>,
    notes_repository: &Option<ugaris_db::PgNotesRepository>,
    anticheat_repository: &Option<ugaris_db::PgAntiCheatRepository>,
    auction_repository: &Option<ugaris_db::PgAuctionRepository>,
) {
    area22::pass_0(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    system::death_1(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    system::macro_track_exp_gain_2(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    system::macro_driver_3(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area22::lostcon_driver_4(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    let merchants_before_tick = system::merchant_actions_5(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    arena::aclerk_driver_6(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    system::bank_driver_7(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    system::trader_driver_8(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area30::clanmaster_driver_9(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area30::clanclerk_driver_10(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area13::dungeonmaster_11(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area13::dungeondoor_12(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area13::dungeonfighter_13(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    arena::clubmaster_driver_14(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::lastseen_15(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::acstatus_16(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::querystats_17(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::jail_18(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::jail_19(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::change_area_20(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area13::build_remove_tile_21(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::rmdeath_22(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::complain_23(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::god_24(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::rename_25(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::lockname_26(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::punish_27(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::unpunish_28(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::exterminate_29(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::look_30(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::klog_31(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::showvalues_32(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::values_33(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::allow_34(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area32::military_master_driver_35(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area30::military_advisor_driver_36(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area13::tick_clan_37(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    arena::master_driver_38(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    arena::fighter_driver_39(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    arena::manager_driver_40(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::camhermit_driver_41(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::yoakin_driver_42(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::terion_driver_43(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::gwendylon_driver_44(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::gwendylon_driver_45(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::greeter_driver_46(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::jessica_driver_47(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::jiu_driver_48(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::forest_ranger_driver_49(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::gate_welcome_driver_50(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area22::gate_fight_driver_51(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    system::janitor_driver_52(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    system::merchant_driver_53(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
        &merchants_before_tick,
    )
    .await;
    system::maintenance_60s_task_54(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    system::maintenance_60s_task_55(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    system::world_56(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area32::world_57(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area32::world_58(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    admin_tasks::player_update_59(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    system::init_event_system_60(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    system::tick_player_61(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::brithildie_driver_62(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::nook_driver_63(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::lydia_driver_64(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::robber_driver_65(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::sanoa_driver_66(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::asturin_driver_67(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::reskin_driver_68(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::guiwynn_driver_69(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::james_driver_70(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::balltrap_driver_71(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area1::logain_driver_72(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area2::superior_driver_73(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area2::moonie_driver_74(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area2::vampire_driver_75(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area2::vampire2_driver_76(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area3::astro1_driver_77(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area3::astro2_driver_80(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area3::thomas_driver_78(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area3::sir_jones_driver_79(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area3::seymour_driver_81(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area3::kelly_driver_82(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area3::carlos_driver_83(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area3::kassim_driver_84(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area3::supermax_driver_85(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area3::lampghost_driver_86(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area4::tester_driver_87(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area8::fdemon_demon_driver_88(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area8::fdemon_boss_driver_89(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area11::islena_driver_90(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area11::palace_guard_driver_91(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area12::golemkeyhold_driver_92(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area3::clara_driver_93(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area16::forest_imp_driver_94(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area16::forest_william_driver_95(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area16::forest_hermit_driver_96(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area17::two_skelly_driver_97(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area17::two_alchemist_driver_98(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area17::two_sanwyn_driver_99(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area17::two_barkeeper_driver_100(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area17::two_guard_driver_101(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area17::two_servant_driver_102(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area17::two_thiefguard_driver_103(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
    area17::two_thiefmaster_driver_104(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area19::nomad_driver_105(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area19::madhermit_driver_106(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area20::lqnpc_driver_107(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area22::labgnome_driver_108(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area22::lab2herald_driver_109(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area22::lab2deamon_driver_110(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area22::lab3passguard_driver_111(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area22::lab3prisoner_driver_112(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area22::lab4seyan_driver_113(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area22::lab4gnalb_driver_114(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area22::lab5seyan_driver_115(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;

    area22::lab5daemon_driver_116(
        &mut *world,
        &mut *runtime,
        &mut *zone_loader,
        config,
        args,
        completed_actions,
        achievement_repository,
        character_repository,
        area_repository,
        clan_repository,
        clan_log_repository,
        merchant_repository,
        military_master_storage_repository,
        military_advisor_storage_repository,
        notes_repository,
        anticheat_repository,
        auction_repository,
    )
    .await;
}
