//! `CDR_FDEMON_ARMY` combat: `NT_TEXT` mission-command reception plus the
//! self-defense/support-caster fallback (`src/area/8/fdemon.c:1338-1431,
//! 1484-1497`). Split out of `fdemon_army.rs` to keep that file within the
//! ~800-line NPC-file guideline (see its own doc comment).
//!
//! Ports:
//! - C `fdemon_army`'s own `NT_CHAR` handling (`fdemon.c:1349-1368`:
//!   `leader_cn` tracking plus the bless/heal support-caster target
//!   selection) as [`World::fdemon_army_scan_sightings`], a direct per-
//!   tick radius scan rather than message-driven - same "replace message-
//!   driven sighting with a direct scan" precedent already established by
//!   `fdemon_demon.rs`/`fdemon_boss.rs` (see their own module doc
//!   comments) - since the `NT_CHAR` messages this substitutes for are
//!   themselves only ever generated by a `notify_area` sighting broadcast
//!   within the same fixed radius this scan reproduces.
//! - `standard_message_driver(cn, msg, 1, 1)`'s `NT_GOTHIT`/`NT_SEEHIT`
//!   cases (`drvlib.c:2478-2538`, hardcoded `agressive=1, helper=1` at
//!   `fdemon_army`'s own call site, `fdemon.c:1429`) as part of
//!   [`World::fdemon_army_process_messages`] (renamed from the previous
//!   `fdemon_army_process_text_messages`, which only handled `NT_TEXT` and
//!   silently discarded every other message type it drained - these two
//!   message kinds are genuine combat *events*, not sightings, so they
//!   stay message-driven; reuses the same `simple_baddy_can_add_standard_
//!   enemy`/`simple_baddy_seen_hit_enemy`/`add_simple_baddy_enemy_
//!   unchecked` machinery every other `aggressive=1, helper=1`
//!   `CDR_SIMPLEBADDY` caller already goes through, `world::npc_messages`).
//!   `standard_message_driver`'s `NT_CHAR` case is *not* duplicated here -
//!   see [`World::fdemon_army_scan_sightings`], which already covers it
//!   via the same `simple_baddy_can_add_standard_enemy(..., priority: 0,
//!   require_visible: true, hurtme: false)` shape.
//! - The self-defense/support-caster fallback that sits between
//!   `fdemon_army`'s two mission-dispatch `switch` blocks (`fdemon.c:1484-
//!   1497`: `fight_driver_update` + heal-a-hurt-friend + bless-a-lower-
//!   ranked-friend + attack-a-visible-enemy) as [`World::
//!   fdemon_army_try_heal`]/[`World::fdemon_army_try_bless`] plus a direct
//!   call to the already-ported [`World::fight_driver_attack_visible_and_
//!   follow`] from [`World::fdemon_army_tick`] (`fdemon_army.rs`) - that
//!   function is driver-state-agnostic (keyed on the driver-independent
//!   `Character::fight_driver` slot, not `CharacterDriverState::
//!   SimpleBaddy`), so it works unchanged for a `FdemonArmy` soldier.
//!
//! Still not ported (documented, not silent): `fight_driver_note_hit`'s
//! `DRD_FIGHTDRIVER.lasthit` write on `NT_GOTHIT` is skipped for a
//! `FdemonArmy` character (the existing shared `NoteHit` outcome handler,
//! `world::npc_messages`, only writes it for `CharacterDriverState::
//! SimpleBaddy` - a soldier never calls `regenerate_simple_baddy`, the
//! only reader of that field, so this is inconsequential in practice, see
//! `fdemon_army.rs`'s own doc comment); the whole `struct emote`
//! personality/chat system (`do_emote`/`got_emote`); `platoon_exp`'s
//! soldier-exp/promotion loop.

use crate::{
    character_driver::{
        analyse_text_qa, analyse_text_qa_needs_name, CharacterDriverState, TextAnalysisOutcome,
    },
    world::*,
};

use super::{FDEMON_ARMY_EMOTE_QA, FDEMON_QA};

/// C `analyse_text_driver`'s own `char_dist(cn, co) > 12` early-out
/// (`fdemon.c:209-211`), same range every other area-8 driver's `NT_TEXT`
/// handling reproduces (see `fdemon_boss.rs`'s `FDEMON_BOSS_TALK_RANGE`).
const FDEMON_ARMY_TALK_RANGE: i32 = 12;

/// Matches `world::text::notify_area`'s own `NOTIFY_SIZE` broadcast radius
/// - same "replace message-driven sighting with a direct scan" precedent
///   as `fdemon_demon.rs`'s own constant of the same name.
const SIGHTING_SCAN_RADIUS: u16 = 32;

impl World {
    /// C `fdemon_army`'s own `NT_CHAR` handling (`fdemon.c:1349-1368`) plus
    /// `standard_message_driver`'s `NT_CHAR` case (`drvlib.c:2470-2476`,
    /// `agressive=1` hardcoded at the call site) - see the module doc
    /// comment for why this is a direct scan instead of message-driven.
    /// Updates `dat.leader_cn` from any visible same-group `CF_PLAYER`
    /// character, adds every visible non-group `is_valid_enemy` target to
    /// the driver-independent `Character::fight_driver` enemy list
    /// (`fight_driver_add_enemy(cn, co, 0, 1)`), and returns `(bless_
    /// target, heal_target)` - the last qualifying same-group candidate
    /// found this tick (C's per-message overwrite; iteration order is not
    /// literally C's message order, but there is normally at most one
    /// player leader plus up to `MAXSOLDIER` fellow soldiers in range, so
    /// this rarely matters in practice).
    pub(crate) fn fdemon_army_scan_sightings(
        &mut self,
        soldier_id: CharacterId,
    ) -> (Option<CharacterId>, Option<CharacterId>) {
        let Some(soldier) = self.characters.get(&soldier_id).cloned() else {
            return (None, None);
        };
        if !matches!(
            soldier.driver_state,
            Some(CharacterDriverState::FdemonArmy(_))
        ) {
            return (None, None);
        }

        let daylight = self.date.daylight;
        let min_x = soldier.x.saturating_sub(SIGHTING_SCAN_RADIUS);
        let max_x = soldier.x.saturating_add(SIGHTING_SCAN_RADIUS);
        let min_y = soldier.y.saturating_sub(SIGHTING_SCAN_RADIUS);
        let max_y = soldier.y.saturating_add(SIGHTING_SCAN_RADIUS);
        let sighted: Vec<Character> = self
            .characters
            .values()
            .filter(|other| {
                other.id != soldier_id
                    && other.x >= min_x
                    && other.x <= max_x
                    && other.y >= min_y
                    && other.y <= max_y
                    && !other.flags.contains(CharacterFlags::DEAD)
            })
            .cloned()
            .collect();

        let current_tick_u32 = self.tick.0 as u32;
        let mut new_leader = None;
        let mut bless_target = None;
        let mut heal_target = None;
        let mut new_enemies = Vec::new();

        for other in &sighted {
            if !char_see_char(&soldier, other, &self.map, daylight) {
                continue;
            }
            if other.group == soldier.group {
                if other.flags.contains(CharacterFlags::PLAYER) {
                    new_leader = Some(other.id);
                }
                // C: `if (ch[co].group == ch[cn].group && cn != co) { ...
                // }` - `cn != co` already holds (`other.id != soldier_id`
                // filtered above).
                if character_value(&soldier, CharacterValue::Bless) > 0
                    && character_value_present(&soldier, CharacterValue::Bless)
                        > character_value_present(other, CharacterValue::Bless)
                    && soldier.mana >= BLESS_COST
                    && may_add_spell(other, &self.items, IDR_BLESS, current_tick_u32).is_some()
                {
                    bless_target = Some(other.id);
                }
                if character_value(&soldier, CharacterValue::Heal) > 0
                    && other.hp
                        < character_value_present(other, CharacterValue::Hp) * POWERSCALE / 3
                    && soldier.mana >= POWERSCALE * 4
                {
                    heal_target = Some(other.id);
                }
            } else if self.simple_baddy_can_add_standard_enemy(soldier_id, other.id, true, false) {
                new_enemies.push(other.id);
            }
        }

        if let Some(leader_id) = new_leader {
            if let Some(CharacterDriverState::FdemonArmy(dat)) = self
                .characters
                .get_mut(&soldier_id)
                .and_then(|character| character.driver_state.as_mut())
            {
                dat.leader_cn = leader_id;
            }
        }

        if !new_enemies.is_empty() {
            let tick = self.tick.0 as i32;
            for enemy_id in new_enemies {
                if let Some(character) = self.characters.get_mut(&soldier_id) {
                    let _ = add_simple_baddy_enemy_unchecked(character, enemy_id, 0, tick);
                }
            }
            self.sort_simple_baddy_enemies_like_c(soldier_id);
        }

        (bless_target, heal_target)
    }

    /// C `fdemon_army`'s own `if (heal && do_heal(cn, heal))` branch
    /// (`fdemon.c:1486-1489`).
    pub(crate) fn fdemon_army_try_heal(
        &mut self,
        soldier_id: CharacterId,
        target_id: CharacterId,
    ) -> bool {
        let Some(target) = self.characters.get(&target_id).cloned() else {
            return false;
        };
        let weather_movement_percent = self.settings.weather_movement_percent;
        self.characters.get_mut(&soldier_id).is_some_and(|caster| {
            do_heal(caster, &target, None, &self.map, weather_movement_percent).is_ok()
        })
    }

    /// C `fdemon_army`'s own `if (bless && do_bless(cn, bless))` branch
    /// (`fdemon.c:1490-1492`).
    pub(crate) fn fdemon_army_try_bless(
        &mut self,
        soldier_id: CharacterId,
        target_id: CharacterId,
    ) -> bool {
        let Some(target) = self.characters.get(&target_id).cloned() else {
            return false;
        };
        let weather_movement_percent = self.settings.weather_movement_percent;
        let current_tick = self.tick.0 as u32;
        self.characters.get_mut(&soldier_id).is_some_and(|caster| {
            do_bless(
                caster,
                &target,
                &self.items,
                current_tick,
                None,
                &self.map,
                weather_movement_percent,
            )
            .is_ok()
        })
    }

    /// C `fdemon_army`'s `NT_TEXT`/`NT_DEAD`/`NT_GOTHIT`/`NT_SEEHIT` message
    /// handling (`fdemon.c:1338-1431`, the message loop's `NT_TEXT`/
    /// `NT_DEAD` cases plus the trailing unconditional `standard_message_
    /// driver(cn, msg, 1, 1)` call for every message). `NT_TEXT`'s `res >=
    /// 20` emote-reaction dispatch (`got_emote`) and case `7`'s emote-stats
    /// debug dump both live in [`World::fdemon_army_process_text_message`]/
    /// [`fdemon_army_emote.rs`](super::fdemon_army_emote) now that the
    /// emote system is ported. `NT_CHAR` is handled separately by
    /// [`World::fdemon_army_scan_sightings`] (a direct scan, not message-
    /// driven) - see that function's own doc comment for why.
    pub fn fdemon_army_process_messages(&mut self, soldier_id: CharacterId) {
        let Some(soldier_name) = self.characters.get(&soldier_id).map(|c| c.name.clone()) else {
            return;
        };
        let messages = self
            .characters
            .get_mut(&soldier_id)
            .map(|character| std::mem::take(&mut character.driver_messages))
            .unwrap_or_default();

        let tick = self.tick.0 as i32;
        for message in messages {
            match message.message_type {
                NT_TEXT => {
                    self.fdemon_army_process_text_message(&soldier_name, soldier_id, &message);
                }
                NT_GOTHIT => {
                    // C `standard_message_driver`'s `NT_GOTHIT` case
                    // (`drvlib.c:2512-2538`): `fight_driver_note_hit` is
                    // skipped here - see the module doc comment.
                    if message.dat1 > 0 {
                        let target_id = CharacterId(message.dat1 as u32);
                        if self
                            .simple_baddy_can_add_standard_enemy(soldier_id, target_id, false, true)
                        {
                            if let Some(character) = self.characters.get_mut(&soldier_id) {
                                let _ =
                                    add_simple_baddy_enemy_unchecked(character, target_id, 1, tick);
                            }
                            self.sort_simple_baddy_enemies_like_c(soldier_id);
                        }
                    }
                }
                NT_DEAD => {
                    // C `if (msg->type == NT_DEAD && msg->dat2 == cn) {
                    // dat->emote.praise += dat->emote.bigmouth; }`
                    // (`fdemon.c:1425-1427`, `dat1`=victim, `dat2`=killer).
                    if message.dat2 == soldier_id.0 as i32 {
                        if let Some(CharacterDriverState::FdemonArmy(dat)) = self
                            .characters
                            .get_mut(&soldier_id)
                            .and_then(|character| character.driver_state.as_mut())
                        {
                            dat.emote.praise += dat.emote.bigmouth;
                        }
                    }
                }
                NT_SEEHIT
                    // C `standard_message_driver`'s `NT_SEEHIT` case
                    // (`drvlib.c:2478-2510`): help whichever side (victim
                    // or attacker) is our platoon-mate.
                    if message.dat1 > 0 && message.dat2 > 0 => {
                        let attacker_id = CharacterId(message.dat1 as u32);
                        let victim_id = CharacterId(message.dat2 as u32);
                        if let Some((target_id, hurtme)) =
                            self.simple_baddy_seen_hit_enemy(soldier_id, attacker_id, victim_id)
                        {
                            if let Some(character) = self.characters.get_mut(&soldier_id) {
                                let priority = if hurtme { 1 } else { 0 };
                                let _ = add_simple_baddy_enemy_unchecked(
                                    character, target_id, priority, tick,
                                );
                            }
                            self.sort_simple_baddy_enemies_like_c(soldier_id);
                        }
                    }
                _ => {}
            }
        }
    }

    fn fdemon_army_process_text_message(
        &mut self,
        soldier_name: &str,
        soldier_id: CharacterId,
        message: &CharacterDriverMessage,
    ) {
        let speaker_id = CharacterId(message.dat3 as u32);
        if speaker_id == soldier_id {
            return;
        }
        let Some(text) = message.text.as_deref() else {
            return;
        };

        let Some(CharacterDriverState::FdemonArmy(dat)) = self
            .characters
            .get(&soldier_id)
            .and_then(|character| character.driver_state.clone())
        else {
            return;
        };
        // C `if ((friend = find_platoon(co, dat)) == -1) { remove_
        // message(...); continue; }` - only platoon members (leader or
        // fellow soldiers) may address this soldier.
        let Some(friend_slot) = dat.platoon.iter().position(|&id| id == speaker_id) else {
            return;
        };

        let (Some(soldier), Some(speaker)) = (
            self.characters.get(&soldier_id),
            self.characters.get(&speaker_id),
        ) else {
            return;
        };
        let daylight = self.date.daylight;
        // C `analyse_text_driver`'s own `char_dist(cn, co) > 12` /
        // `!char_see_char(cn, co)` early-outs (`fdemon.c:209-215`).
        if char_dist(soldier, speaker) > FDEMON_ARMY_TALK_RANGE
            || !char_see_char(soldier, speaker, &self.map, daylight)
        {
            return;
        }
        let speaker_name = speaker.name.clone();
        let speaker_military_points = speaker.military_points;
        let (soldier_x, soldier_y) = (soldier.x, soldier.y);

        // C's single shared `qa[]` table holds both the `needs_name: 0`
        // small-talk/command rows and the `needs_name: 1` emote-reaction
        // rows in one array, tried in declaration order by one `analyse_
        // text_driver` call; this port keeps them in two separate tables
        // (see `character_driver::analyse_text_qa_needs_name`'s own doc
        // comment for why) and tries the small-talk table first, matching
        // C's row order (small talk is declared before the emote rows).
        let outcome = match analyse_text_qa(text, soldier_name, &speaker_name, FDEMON_QA) {
            TextAnalysisOutcome::NoMatch => {
                analyse_text_qa_needs_name(text, soldier_name, &speaker_name, FDEMON_ARMY_EMOTE_QA)
            }
            matched => matched,
        };

        // C `if (res >= 20) { got_emote(cn, co, friend, res, dat); }`
        // (`fdemon.c:1380-1382`) - runs for *any* platoon member, not just
        // the leader, before the leader-only command gate below.
        if let TextAnalysisOutcome::Matched(code) = outcome {
            if code >= 20 {
                self.fdemon_army_got_emote(soldier_id, speaker_id, friend_slot, code);
            }
        }

        // C `if (co != dat->leader_cn) { remove_message(...); continue; }`
        // - only the leader's own speech may issue a mission command; a
        // fellow soldier's matching text is dropped here (C's own `find_
        // platoon` check above already filters out anyone not on the
        // platoon at all).
        if speaker_id != dat.leader_cn {
            return;
        }

        let rank_name = army_rank_name(army_rank_for_points(speaker_military_points)).to_string();

        match outcome {
            TextAnalysisOutcome::Matched(2) => {
                self.npc_say(soldier_id, &format!("Sir! Yes, Sir, {rank_name}, Sir!"));
                self.set_fdemon_army_mission(soldier_id, MIS_FOLLOW);
            }
            TextAnalysisOutcome::Matched(3) => {
                self.npc_say(soldier_id, &format!("Will do, {rank_name}."));
                let tick = self.tick.0 as i64;
                if let Some(CharacterDriverState::FdemonArmy(dat)) = self
                    .characters
                    .get_mut(&soldier_id)
                    .and_then(|character| character.driver_state.as_mut())
                {
                    dat.mission = MIS_BACK;
                    dat.opt1 = i32::from(soldier_x);
                    dat.opt2 = i32::from(soldier_y);
                    dat.timer = tick;
                }
            }
            TextAnalysisOutcome::Matched(4) => {
                self.npc_say(soldier_id, &format!("Aye Aye {rank_name}, Sir."));
                self.set_fdemon_army_mission(soldier_id, MIS_RETREAT);
            }
            TextAnalysisOutcome::Matched(5) => {
                self.npc_say(soldier_id, &format!("So be it, {rank_name}."));
                self.set_fdemon_army_mission(soldier_id, MIS_FRONT);
            }
            TextAnalysisOutcome::Matched(6) => {
                self.npc_say(soldier_id, &format!("I'll go rub his back, {rank_name}."));
                self.set_fdemon_army_mission(soldier_id, MIS_BEHIND);
            }
            TextAnalysisOutcome::Matched(7) => {
                // C `case 7: say(cn, "cuddly=%d, ...", ...); break;`
                // (`fdemon.c:1414-1421`).
                if let Some(line) = self.fdemon_army_emote_stats_line(soldier_id) {
                    self.npc_say(soldier_id, &line);
                }
            }
            TextAnalysisOutcome::Said(_)
            | TextAnalysisOutcome::Matched(_)
            | TextAnalysisOutcome::NoMatch => {}
        }
    }
}
